apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: publishing-platform
spec:
  rules:
    - host: publishing.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: publishing-platform
                port:
                  number: 4321
